#ifndef PREDEF_PATTERNS_H
#define PREDEF_PATTERNS_H
#include <stdint.h>
#include "pattern.h"

// Firmware-internal API. Reads predefined-pattern records from the INCBIN'd
// blob (generated by panel/tools/gen_predef_patterns.py at build time).
//
// V1 catalog:
//   slot   0     : "ERR"      (canonical fallback error glyph; required)
//   slots 1..99  : PE01..PE99 (only PE01-PE05 populated)
//   slots 100..199: CE00..CE99 (only CE00 populated)
//   slots 200+    : reserved for V3 test/calibration patterns
//
// load_into() returns false on unprogrammed/out-of-range slots; callers
// should fall back to slot 0 (or to the compiled-in fallback ERR glyph
// if even slot 0 fails — see predef_patterns.cpp).
//
// **API note:** this interface is firmware-internal. V3 may revise the blob
// format and on-flash layout; do not expose `slot` identifiers as a stable
// external contract beyond the 0xC2 wire-protocol opcode's index field.
namespace predef {

    // Validate the blob's magic + version. Logs to serial on mismatch but
    // never blocks boot — error-display still works via the compiled-in
    // fallback in load_fallback_err().
    bool init();

    // Look up `slot` in the TOC; if populated, unpack pixels into `dst`
    // (which is forced to Gray_2 Persistent at the blob's default_duty_cycle).
    // Returns true on success.
    bool load_into(Pattern &dst, uint32_t slot);

    // Hard-coded compiled-in fallback ERR glyph (1bpp, 20x20). Used when the
    // INCBIN'd blob is missing/corrupt or even slot 0 lookup fails. Same
    // pixel layout as the build-time generator's "ERR" composition.
    void load_fallback_err(Pattern &dst);

    // Slot count reported by the blob (0 if blob invalid).
    uint16_t pattern_count();

    // True if init() ran successfully and the blob is valid.
    bool blob_valid();

}

#endif
