#include "predef_patterns.h"
#include "predef_patterns_blob.h"
#include "predef_patterns_table.h"
#include "protocol.h"
#include <Streaming.h>
#include <string.h>

// V1 predefined-pattern loader. The blob is generated by
// panel/tools/gen_predef_patterns.py and #include'd above. Layout matches
// the format documented in that script's docstring (LE throughout):
//   Header(16) -> TOC entries (8B each) -> payload records.

namespace {

// Magic word: 4 ASCII bytes "G6PP" at the start of the blob.
constexpr uint8_t kMagic[4] = { 'G', '6', 'P', 'P' };

constexpr uint16_t kExpectedVersion = 0x0001;
constexpr size_t kHeaderBytes = 16;
constexpr size_t kTocEntryBytes = 8;
constexpr uint8_t kFormatGray2 = 0;

// Cached after init() — pulled from the blob header so load_into() avoids
// re-parsing on every error raise.
uint16_t g_pattern_count = 0;
uint32_t g_toc_offset = 0;
bool g_blob_valid = false;

// Endian-safe little-endian reads (the blob is LE per spec; matches RP2350's
// native byte order, but read byte-by-byte so we don't rely on alignment).
inline uint16_t read_u16(const uint8_t *p) {
    return uint16_t(p[0]) | (uint16_t(p[1]) << 8);
}
inline uint32_t read_u32(const uint8_t *p) {
    return uint32_t(p[0]) | (uint32_t(p[1]) << 8)
         | (uint32_t(p[2]) << 16) | (uint32_t(p[3]) << 24);
}

// Hard-coded fallback "ERR" glyph used when the blob is invalid or slot 0
// itself fails to load. 50 bytes Gray_2 packed MSB-first. Generated by the
// build-time tool too, but kept here as a compile-time constant so the
// error display still works under absolute worst case.
// 50 bytes Gray_2 packed, MSB-first, row-major. Extracted from the build-
// time generator's output for text="ERR" — regenerate to validate via:
//   python3 -c "import sys; sys.path.insert(0, 'panel/tools'); \
//     import gen_predef_patterns as g; \
//     print(', '.join(hex(b) for b in g.pack_gray_2(g.compose_2_char('ERR'))))"
constexpr uint8_t kFallbackErrGlyph[50] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x0F, 0x9E, 0x00, 0x81, 0x10,
    0x08, 0x11, 0x00, 0xF1, 0xE0, 0x08, 0x14, 0x00, 0x81, 0x20,
    0x0F, 0x91, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1E, 0x00,
    0x01, 0x10, 0x00, 0x11, 0x00, 0x01, 0xE0, 0x00, 0x14, 0x00,
    0x01, 0x20, 0x00, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

constexpr uint8_t kFallbackDutyCycle = 192;

}  // namespace


namespace predef {

bool init() {
    using namespace predef_blob_data;
    if (kPredefBlobSize < kHeaderBytes) {
        Serial << "predef: blob too small (" << kPredefBlobSize << " bytes)" << endl;
        g_blob_valid = false;
        return false;
    }
    if (memcmp(kPredefBlob, kMagic, sizeof(kMagic)) != 0) {
        Serial << "predef: bad magic; expected G6PP" << endl;
        g_blob_valid = false;
        return false;
    }
    uint16_t version = read_u16(kPredefBlob + 4);
    if (version != kExpectedVersion) {
        Serial << "predef: version mismatch (got " << version
               << ", expected " << kExpectedVersion << ")" << endl;
        g_blob_valid = false;
        return false;
    }
    g_pattern_count = read_u16(kPredefBlob + 6);
    g_toc_offset = read_u32(kPredefBlob + 8);
    // Sanity: TOC must fit within the blob.
    uint32_t toc_end = g_toc_offset + uint32_t(g_pattern_count) * kTocEntryBytes;
    if (toc_end > kPredefBlobSize) {
        Serial << "predef: TOC extends past blob end" << endl;
        g_blob_valid = false;
        return false;
    }
    g_blob_valid = true;
    Serial << "predef: ok, " << g_pattern_count
           << " slots (" << kPredefBlobSize << " B)" << endl;
    return true;
}


uint16_t pattern_count() {
    return g_blob_valid ? g_pattern_count : 0;
}


bool blob_valid() {
    return g_blob_valid;
}


bool load_into(Pattern &dst, uint32_t slot) {
    using namespace predef_blob_data;
    if (!g_blob_valid) return false;
    if (slot >= g_pattern_count) return false;

    const uint8_t *entry = kPredefBlob + g_toc_offset + slot * kTocEntryBytes;
    uint32_t payload_off = read_u32(entry);
    uint16_t payload_len = read_u16(entry + 4);
    uint8_t fmt = entry[6];
    if (payload_len == 0) return false;  // unprogrammed slot

    // Bounds check: payload must lie within the blob.
    if (uint64_t(payload_off) + payload_len > kPredefBlobSize) {
        Serial << "predef: slot " << slot << " payload out of bounds" << endl;
        return false;
    }

    if (fmt != kFormatGray2) {
        // V1 only supports Gray_2 in the blob; Gray_16 is reserved for V3.
        Serial << "predef: slot " << slot << " unsupported format " << fmt << endl;
        return false;
    }

    const uint8_t *payload = kPredefBlob + payload_off;
    uint8_t rows = payload[0];
    uint8_t cols = payload[1];
    // payload[2] = format (== fmt); payload[3] = default_duty_cycle.
    uint8_t default_duty = payload[3];

    if (rows != PANEL_SIZE || cols != PANEL_SIZE) {
        Serial << "predef: slot " << slot << " dim mismatch (got "
               << rows << "x" << cols << ")" << endl;
        return false;
    }

    // Unpack Gray_2 (1 bit per pixel, MSB-first, row-major) into the Pattern's
    // matrix. The Pattern matrix stores 8-bit values; for Gray_2, only the
    // low bit is meaningful (precompute_bcm_data treats nonzero as ON).
    const uint8_t *pixels = payload + 4;
    dst.set_gray_level(GrayLevel::Gray_2);
    dst.set_duty_cycle(default_duty);
    dst.set_mode(DisplayMode::Persistent);
    size_t bit_idx = 0;
    for (size_t r = 0; r < PANEL_SIZE; r++) {
        for (size_t c = 0; c < PANEL_SIZE; c++) {
            size_t byte_idx = bit_idx >> 3;
            size_t bit_pos = 7 - (bit_idx & 7);
            dst.at(r, c) = (pixels[byte_idx] >> bit_pos) & 1;
            bit_idx++;
        }
    }
    return true;
}


void load_fallback_err(Pattern &dst) {
    dst.set_gray_level(GrayLevel::Gray_2);
    dst.set_duty_cycle(kFallbackDutyCycle);
    dst.set_mode(DisplayMode::Persistent);
    size_t bit_idx = 0;
    for (size_t r = 0; r < PANEL_SIZE; r++) {
        for (size_t c = 0; c < PANEL_SIZE; c++) {
            size_t byte_idx = bit_idx >> 3;
            size_t bit_pos = 7 - (bit_idx & 7);
            dst.at(r, c) = (kFallbackErrGlyph[byte_idx] >> bit_pos) & 1;
            bit_idx++;
        }
    }
}

}  // namespace predef
